# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smart_city.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'smart_city.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10smart_city.proto\x12\nsmart_city\"R\n\x15TemperatureSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"q\n\x14\x41irQualitySensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63\x61rbon_monoxide\x18\x02 \x01(\x02\x12\x1a\n\x12particulate_matter\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"D\n\x0f\x41\x63tuatorCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"1\n\x0c\x44\x65viceStatus\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"I\n\x10\x44iscoveryMessage\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_city_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATURESENSORDATA']._serialized_start=32
  _globals['_TEMPERATURESENSORDATA']._serialized_end=114
  _globals['_AIRQUALITYSENSORDATA']._serialized_start=116
  _globals['_AIRQUALITYSENSORDATA']._serialized_end=229
  _globals['_ACTUATORCOMMAND']._serialized_start=231
  _globals['_ACTUATORCOMMAND']._serialized_end=299
  _globals['_DEVICESTATUS']._serialized_start=301
  _globals['_DEVICESTATUS']._serialized_end=350
  _globals['_DISCOVERYMESSAGE']._serialized_start=352
  _globals['_DISCOVERYMESSAGE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
